spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://119.23.242.234:9306/wxdc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


server:
  port: 8081




